library("shiny")
library("shinyjs")
library("shinyBS")
library("shinythemes")
library("shinyWidgets")
library("ECharts2Shiny")
library("shinydashboard")
library("shinycssloaders")
library("leaflet")
library("rgdal")
library("tidyverse")
setwd("C:/Users/Elvins Moraes/Desktop/edu/Projeto - Geopolitica")
runApp()
